// File: __KCM_SMS.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

public abstract class __KCM_SMS extends ezjcom.JComEventListener {

	/** Default constructor for COM-event listener object */

	public __KCM_SMS()
	{
		try{
			__JComEventListenerInit();
		} catch (ezjcom.JComException ex) {
			throw new RuntimeException( ex.toString());
		}
	}

	/** JNI functions used internally by EZ-JCom */
	private native boolean __JComEventListenerInit() throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

