// File: _KCM_SMS.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class _KCM_SMS extends ezjcom.JComObject {

	public native SMS._Connection getMSSQL_CONN() throws ezjcom.JComException;

	public native void setMSSQL_CONN(SMS._Connection arg) throws ezjcom.JComException;

	public native SMS._Recordset getH_RS() throws ezjcom.JComException;

	public native void setH_RS(SMS._Recordset arg) throws ezjcom.JComException;

	public native SMS._Recordset getH_DS() throws ezjcom.JComException;

	public native void setH_DS(SMS._Recordset arg) throws ezjcom.JComException;

	public native boolean getSt() throws ezjcom.JComException;

	public native void setSt(boolean arg) throws ezjcom.JComException;

	public native String getI_D() throws ezjcom.JComException;

	public native void setI_D(String arg) throws ezjcom.JComException;

	public native String getP_W() throws ezjcom.JComException;

	public native void setP_W(String arg) throws ezjcom.JComException;

	public native short getM_C() throws ezjcom.JComException;

	public native void setM_C(short arg) throws ezjcom.JComException;

	public native String getS_D() throws ezjcom.JComException;

	public native void setS_D(String arg) throws ezjcom.JComException;

	public native String getC_B() throws ezjcom.JComException;

	public native void setC_B(String arg) throws ezjcom.JComException;

	public native String getS_M() throws ezjcom.JComException;

	public native void setS_M(String arg) throws ezjcom.JComException;

	public native String getM_L() throws ezjcom.JComException;

	public native void setM_L(String arg) throws ezjcom.JComException;

	public native boolean getX_DB_CONN_ANC() throws ezjcom.JComException;

	public native void setX_DB_CONN_ANC(boolean arg) throws ezjcom.JComException;

	/** Sending_sms. 
	 * <P>  Parameter <i>id</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>pass</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>msg_count</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>Sending_datatime</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>Sending_msg</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>man_list_and_Phone_no</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>Call_back_no</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 */
	public native String Sending_sms(String[] id, 
		String[] pass, 
		short[] msg_count, 
		String[] Sending_datatime, 
		String[] Sending_msg, 
		String[] man_list_and_Phone_no, 
		String[] Call_back_no) throws ezjcom.JComException;

	public native void sms_sending() throws ezjcom.JComException;

	public native void sms_sending2() throws ezjcom.JComException;

	public native double get_Carge_sms() throws ezjcom.JComException;

	/** X_SMS_COUNT_DSIP. 
	 * <P>  Parameter <i>Z_ID</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 * <BR> Parameter <i>Z_PASS</i> is an IN/OUT parameter.  It requires an initialized array of size 1.
	 */
	public native double X_SMS_COUNT_DSIP(ezjcom.JComVariant[] Z_ID, 
		ezjcom.JComVariant[] Z_PASS) throws ezjcom.JComException;

	public native ezjcom.JComVariant X_MSSQL_DB_OPEN() throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private _KCM_SMS() {}
	private _KCM_SMS( java.lang.ref.Reference ref ) {}

	private _KCM_SMS( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"_KCM_SMS\"" );
	}

	/** Use this method only for creating a COM interface of type _KCM_SMS
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static _KCM_SMS _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new _KCM_SMS(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

