// File: _Stream.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class _Stream extends ezjcom.JComObject {

	public native int getSize() throws ezjcom.JComException;

	public native boolean getEOS() throws ezjcom.JComException;

	public native int getPosition() throws ezjcom.JComException;

	public native void setPosition(int arg) throws ezjcom.JComException;

	public native SMS.StreamTypeEnum getType() throws ezjcom.JComException;

	public native void setType(SMS.StreamTypeEnum arg) throws ezjcom.JComException;

	public native SMS.LineSeparatorEnum getLineSeparator() throws ezjcom.JComException;

	public native void setLineSeparator(SMS.LineSeparatorEnum arg) throws ezjcom.JComException;

	public native SMS.ObjectStateEnum getState() throws ezjcom.JComException;

	public native SMS.ConnectModeEnum getMode() throws ezjcom.JComException;

	public native void setMode(SMS.ConnectModeEnum arg) throws ezjcom.JComException;

	public native String getCharset() throws ezjcom.JComException;

	public native void setCharset(String arg) throws ezjcom.JComException;

	public native ezjcom.JComVariant Read(int NumBytes) throws ezjcom.JComException;

	public native void Open(ezjcom.JComVariant Source, SMS.ConnectModeEnum Mode, SMS.StreamOpenOptionsEnum Options, String UserName, String Password) throws ezjcom.JComException;

	public native void Close() throws ezjcom.JComException;

	public native void SkipLine() throws ezjcom.JComException;

	public native void Write(ezjcom.JComVariant Buffer) throws ezjcom.JComException;

	public native void SetEOS() throws ezjcom.JComException;

	public native void CopyTo(SMS._Stream DestStream, int CharNumber) throws ezjcom.JComException;

	public native void Flush() throws ezjcom.JComException;

	public native void SaveToFile(String FileName, SMS.SaveOptionsEnum Options) throws ezjcom.JComException;

	public native void LoadFromFile(String FileName) throws ezjcom.JComException;

	public native String ReadText(int NumChars) throws ezjcom.JComException;

	public native void WriteText(String Data, SMS.StreamWriteEnum Options) throws ezjcom.JComException;

	public native void Cancel() throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private _Stream() {}
	private _Stream( java.lang.ref.Reference ref ) {}

	private _Stream( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"_Stream\"" );
	}

	/** Use this method only for creating a COM interface of type _Stream
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static _Stream _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new _Stream(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

