// File: ADCPROP_UPDATECRITERIA_ENUM.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ADCPROP_UPDATECRITERIA_ENUM enumerated type */
public class ADCPROP_UPDATECRITERIA_ENUM extends ezjcom.JComEnumeration {


	/** enumerated constant adCriteriaKey */
	public static ADCPROP_UPDATECRITERIA_ENUM adCriteriaKey = new ADCPROP_UPDATECRITERIA_ENUM(0);

	/** enumerated constant adCriteriaAllCols */
	public static ADCPROP_UPDATECRITERIA_ENUM adCriteriaAllCols = new ADCPROP_UPDATECRITERIA_ENUM(1);

	/** enumerated constant adCriteriaUpdCols */
	public static ADCPROP_UPDATECRITERIA_ENUM adCriteriaUpdCols = new ADCPROP_UPDATECRITERIA_ENUM(2);

	/** enumerated constant adCriteriaTimeStamp */
	public static ADCPROP_UPDATECRITERIA_ENUM adCriteriaTimeStamp = new ADCPROP_UPDATECRITERIA_ENUM(3);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ADCPROP_UPDATECRITERIA_ENUM( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ADCPROP_UPDATECRITERIA_ENUM && __obj != null && ((ADCPROP_UPDATECRITERIA_ENUM)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ADCPROP_UPDATECRITERIA_ENUM intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adCriteriaKey;
			case 1: return adCriteriaAllCols;
			case 2: return adCriteriaUpdCols;
			case 3: return adCriteriaTimeStamp;
		}
		return new ADCPROP_UPDATECRITERIA_ENUM(__n);
	}
}

