// File: ADCPROP_UPDATERESYNC_ENUM.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ADCPROP_UPDATERESYNC_ENUM enumerated type */
public class ADCPROP_UPDATERESYNC_ENUM extends ezjcom.JComEnumeration {


	/** enumerated constant adResyncNone */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncNone = new ADCPROP_UPDATERESYNC_ENUM(0);

	/** enumerated constant adResyncAutoIncrement */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncAutoIncrement = new ADCPROP_UPDATERESYNC_ENUM(1);

	/** enumerated constant adResyncConflicts */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncConflicts = new ADCPROP_UPDATERESYNC_ENUM(2);

	/** enumerated constant adResyncUpdates */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncUpdates = new ADCPROP_UPDATERESYNC_ENUM(4);

	/** enumerated constant adResyncInserts */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncInserts = new ADCPROP_UPDATERESYNC_ENUM(8);

	/** enumerated constant adResyncAll */
	public static ADCPROP_UPDATERESYNC_ENUM adResyncAll = new ADCPROP_UPDATERESYNC_ENUM(15);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ADCPROP_UPDATERESYNC_ENUM( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ADCPROP_UPDATERESYNC_ENUM && __obj != null && ((ADCPROP_UPDATERESYNC_ENUM)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ADCPROP_UPDATERESYNC_ENUM intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adResyncNone;
			case 1: return adResyncAutoIncrement;
			case 2: return adResyncConflicts;
			case 4: return adResyncUpdates;
			case 8: return adResyncInserts;
			case 15: return adResyncAll;
		}
		return new ADCPROP_UPDATERESYNC_ENUM(__n);
	}
}

