// File: ADCPROP_ASYNCTHREADPRIORITY_ENUM.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ADCPROP_ASYNCTHREADPRIORITY_ENUM enumerated type */
public class ADCPROP_ASYNCTHREADPRIORITY_ENUM extends ezjcom.JComEnumeration {


	/** enumerated constant adPriorityLowest */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM adPriorityLowest = new ADCPROP_ASYNCTHREADPRIORITY_ENUM(1);

	/** enumerated constant adPriorityBelowNormal */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM adPriorityBelowNormal = new ADCPROP_ASYNCTHREADPRIORITY_ENUM(2);

	/** enumerated constant adPriorityNormal */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM adPriorityNormal = new ADCPROP_ASYNCTHREADPRIORITY_ENUM(3);

	/** enumerated constant adPriorityAboveNormal */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM adPriorityAboveNormal = new ADCPROP_ASYNCTHREADPRIORITY_ENUM(4);

	/** enumerated constant adPriorityHighest */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM adPriorityHighest = new ADCPROP_ASYNCTHREADPRIORITY_ENUM(5);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ADCPROP_ASYNCTHREADPRIORITY_ENUM( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ADCPROP_ASYNCTHREADPRIORITY_ENUM && __obj != null && ((ADCPROP_ASYNCTHREADPRIORITY_ENUM)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ADCPROP_ASYNCTHREADPRIORITY_ENUM intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adPriorityLowest;
			case 2: return adPriorityBelowNormal;
			case 3: return adPriorityNormal;
			case 4: return adPriorityAboveNormal;
			case 5: return adPriorityHighest;
		}
		return new ADCPROP_ASYNCTHREADPRIORITY_ENUM(__n);
	}
}

