// File: AffectEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** AffectEnum enumerated type */
public class AffectEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adAffectCurrent */
	public static AffectEnum adAffectCurrent = new AffectEnum(1);

	/** enumerated constant adAffectGroup */
	public static AffectEnum adAffectGroup = new AffectEnum(2);

	/** enumerated constant adAffectAll */
	public static AffectEnum adAffectAll = new AffectEnum(3);

	/** enumerated constant adAffectAllChapters */
	public static AffectEnum adAffectAllChapters = new AffectEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected AffectEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof AffectEnum && __obj != null && ((AffectEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static AffectEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adAffectCurrent;
			case 2: return adAffectGroup;
			case 3: return adAffectAll;
			case 4: return adAffectAllChapters;
		}
		return new AffectEnum(__n);
	}
}

