// File: BookmarkEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** BookmarkEnum enumerated type */
public class BookmarkEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adBookmarkCurrent */
	public static BookmarkEnum adBookmarkCurrent = new BookmarkEnum(0);

	/** enumerated constant adBookmarkFirst */
	public static BookmarkEnum adBookmarkFirst = new BookmarkEnum(1);

	/** enumerated constant adBookmarkLast */
	public static BookmarkEnum adBookmarkLast = new BookmarkEnum(2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected BookmarkEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof BookmarkEnum && __obj != null && ((BookmarkEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static BookmarkEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adBookmarkCurrent;
			case 1: return adBookmarkFirst;
			case 2: return adBookmarkLast;
		}
		return new BookmarkEnum(__n);
	}
}

