// File: Command15.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class Command15 extends ezjcom.JComObject {

	public native SMS.Properties getProperties() throws ezjcom.JComException;

	public native SMS._Connection getActiveConnection() throws ezjcom.JComException;

	public native void setActiveConnection(SMS._Connection arg) throws ezjcom.JComException;

	public native void setActiveConnection_(ezjcom.JComVariant arg) throws ezjcom.JComException;

	public native String getCommandText() throws ezjcom.JComException;

	public native void setCommandText(String arg) throws ezjcom.JComException;

	public native int getCommandTimeout() throws ezjcom.JComException;

	public native void setCommandTimeout(int arg) throws ezjcom.JComException;

	public native boolean getPrepared() throws ezjcom.JComException;

	public native void setPrepared(boolean arg) throws ezjcom.JComException;

	/** Execute. 
	 * <P>  Parameter <i>RecordsAffected</i> is an OUT parameter.  It requires an array of size 1.
	 * <BR> Parameter <i>Parameters</i> is declared IN-only (not declared as OUT or IN/OUT), therefore EZ JCom will isolate any changes made by the COM method.  (Any changes will not be visible back in Java.)
	 */
	public native SMS._Recordset Execute(ezjcom.JComVariant[] RecordsAffected, 
		ezjcom.JComVariant Parameters, int Options) throws ezjcom.JComException;

	public native SMS._Parameter CreateParameter(String Name, SMS.DataTypeEnum Type, SMS.ParameterDirectionEnum Direction, int Size) throws ezjcom.JComException;

	public native SMS._Parameter CreateParameter(String Name, SMS.DataTypeEnum Type, SMS.ParameterDirectionEnum Direction, int Size, ezjcom.JComVariant Value) throws ezjcom.JComException;

	public native SMS.Parameters getParameters() throws ezjcom.JComException;

	public native void setCommandType(SMS.CommandTypeEnum arg) throws ezjcom.JComException;

	public native SMS.CommandTypeEnum getCommandType() throws ezjcom.JComException;

	public native String getName() throws ezjcom.JComException;

	public native void setName(String arg) throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private Command15() {}
	private Command15( java.lang.ref.Reference ref ) {}

	private Command15( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"Command15\"" );
	}

	/** Use this method only for creating a COM interface of type Command15
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static Command15 _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new Command15(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

