// File: CommandTypeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** CommandTypeEnum enumerated type */
public class CommandTypeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adCmdUnspecified */
	public static CommandTypeEnum adCmdUnspecified = new CommandTypeEnum(-1);

	/** enumerated constant adCmdUnknown */
	public static CommandTypeEnum adCmdUnknown = new CommandTypeEnum(8);

	/** enumerated constant adCmdText */
	public static CommandTypeEnum adCmdText = new CommandTypeEnum(1);

	/** enumerated constant adCmdTable */
	public static CommandTypeEnum adCmdTable = new CommandTypeEnum(2);

	/** enumerated constant adCmdStoredProc */
	public static CommandTypeEnum adCmdStoredProc = new CommandTypeEnum(4);

	/** enumerated constant adCmdFile */
	public static CommandTypeEnum adCmdFile = new CommandTypeEnum(256);

	/** enumerated constant adCmdTableDirect */
	public static CommandTypeEnum adCmdTableDirect = new CommandTypeEnum(512);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected CommandTypeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof CommandTypeEnum && __obj != null && ((CommandTypeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static CommandTypeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adCmdUnspecified;
			case 8: return adCmdUnknown;
			case 1: return adCmdText;
			case 2: return adCmdTable;
			case 4: return adCmdStoredProc;
			case 256: return adCmdFile;
			case 512: return adCmdTableDirect;
		}
		return new CommandTypeEnum(__n);
	}
}

