// File: CompareEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** CompareEnum enumerated type */
public class CompareEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adCompareLessThan */
	public static CompareEnum adCompareLessThan = new CompareEnum(0);

	/** enumerated constant adCompareEqual */
	public static CompareEnum adCompareEqual = new CompareEnum(1);

	/** enumerated constant adCompareGreaterThan */
	public static CompareEnum adCompareGreaterThan = new CompareEnum(2);

	/** enumerated constant adCompareNotEqual */
	public static CompareEnum adCompareNotEqual = new CompareEnum(3);

	/** enumerated constant adCompareNotComparable */
	public static CompareEnum adCompareNotComparable = new CompareEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected CompareEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof CompareEnum && __obj != null && ((CompareEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static CompareEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adCompareLessThan;
			case 1: return adCompareEqual;
			case 2: return adCompareGreaterThan;
			case 3: return adCompareNotEqual;
			case 4: return adCompareNotComparable;
		}
		return new CompareEnum(__n);
	}
}

