// File: ConnectionEvents.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

public abstract class ConnectionEvents extends ezjcom.JComEventListener {

	/** Override this method to process the "InfoMessage" event. 
	  */
	public abstract void InfoMessage(SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "BeginTransComplete" event. 
	  */
	public abstract void BeginTransComplete(int TransactionLevel, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "CommitTransComplete" event. 
	  */
	public abstract void CommitTransComplete(SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "RollbackTransComplete" event. 
	  */
	public abstract void RollbackTransComplete(SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "WillExecute" event. 
	 * <P>Parameter <i>Options</i> is IN/OUT.  It will be passed inside an array of size 1, so it can be modified.
	  */
	public abstract void WillExecute(String Source, SMS.CursorTypeEnum CursorType, SMS.LockTypeEnum LockType, int[] Options, SMS.EventStatusEnum adStatus, SMS._Command pCommand, SMS._Recordset pRecordset, SMS._Connection pConnection);

	/** Override this method to process the "ExecuteComplete" event. 
	  */
	public abstract void ExecuteComplete(int RecordsAffected, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Command pCommand, SMS._Recordset pRecordset, SMS._Connection pConnection);

	/** Override this method to process the "WillConnect" event. 
	 * <P>Parameter <i>Options</i> is IN/OUT.  It will be passed inside an array of size 1, so it can be modified.
	  */
	public abstract void WillConnect(String ConnectionString, String UserID, String Password, int[] Options, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "ConnectComplete" event. 
	  */
	public abstract void ConnectComplete(SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Override this method to process the "Disconnect" event. 
	  */
	public abstract void Disconnect(SMS.EventStatusEnum adStatus, SMS._Connection pConnection);

	/** Default constructor for COM-event listener object */

	public ConnectionEvents()
	{
		try{
			__JComEventListenerInit();
		} catch (ezjcom.JComException ex) {
			throw new RuntimeException( ex.toString());
		}
	}

	/** JNI functions used internally by EZ-JCom */
	private native boolean __JComEventListenerInit() throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

