// File: ConnectModeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ConnectModeEnum enumerated type */
public class ConnectModeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adModeUnknown */
	public static ConnectModeEnum adModeUnknown = new ConnectModeEnum(0);

	/** enumerated constant adModeRead */
	public static ConnectModeEnum adModeRead = new ConnectModeEnum(1);

	/** enumerated constant adModeWrite */
	public static ConnectModeEnum adModeWrite = new ConnectModeEnum(2);

	/** enumerated constant adModeReadWrite */
	public static ConnectModeEnum adModeReadWrite = new ConnectModeEnum(3);

	/** enumerated constant adModeShareDenyRead */
	public static ConnectModeEnum adModeShareDenyRead = new ConnectModeEnum(4);

	/** enumerated constant adModeShareDenyWrite */
	public static ConnectModeEnum adModeShareDenyWrite = new ConnectModeEnum(8);

	/** enumerated constant adModeShareExclusive */
	public static ConnectModeEnum adModeShareExclusive = new ConnectModeEnum(12);

	/** enumerated constant adModeShareDenyNone */
	public static ConnectModeEnum adModeShareDenyNone = new ConnectModeEnum(16);

	/** enumerated constant adModeRecursive */
	public static ConnectModeEnum adModeRecursive = new ConnectModeEnum(4194304);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ConnectModeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ConnectModeEnum && __obj != null && ((ConnectModeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ConnectModeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adModeUnknown;
			case 1: return adModeRead;
			case 2: return adModeWrite;
			case 3: return adModeReadWrite;
			case 4: return adModeShareDenyRead;
			case 8: return adModeShareDenyWrite;
			case 12: return adModeShareExclusive;
			case 16: return adModeShareDenyNone;
			case 4194304: return adModeRecursive;
		}
		return new ConnectModeEnum(__n);
	}
}

