// File: CopyRecordOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** CopyRecordOptionsEnum enumerated type */
public class CopyRecordOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adCopyUnspecified */
	public static CopyRecordOptionsEnum adCopyUnspecified = new CopyRecordOptionsEnum(-1);

	/** enumerated constant adCopyOverWrite */
	public static CopyRecordOptionsEnum adCopyOverWrite = new CopyRecordOptionsEnum(1);

	/** enumerated constant adCopyAllowEmulation */
	public static CopyRecordOptionsEnum adCopyAllowEmulation = new CopyRecordOptionsEnum(4);

	/** enumerated constant adCopyNonRecursive */
	public static CopyRecordOptionsEnum adCopyNonRecursive = new CopyRecordOptionsEnum(2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected CopyRecordOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof CopyRecordOptionsEnum && __obj != null && ((CopyRecordOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static CopyRecordOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adCopyUnspecified;
			case 1: return adCopyOverWrite;
			case 4: return adCopyAllowEmulation;
			case 2: return adCopyNonRecursive;
		}
		return new CopyRecordOptionsEnum(__n);
	}
}

