// File: CursorTypeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** CursorTypeEnum enumerated type */
public class CursorTypeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adOpenUnspecified */
	public static CursorTypeEnum adOpenUnspecified = new CursorTypeEnum(-1);

	/** enumerated constant adOpenForwardOnly */
	public static CursorTypeEnum adOpenForwardOnly = new CursorTypeEnum(0);

	/** enumerated constant adOpenKeyset */
	public static CursorTypeEnum adOpenKeyset = new CursorTypeEnum(1);

	/** enumerated constant adOpenDynamic */
	public static CursorTypeEnum adOpenDynamic = new CursorTypeEnum(2);

	/** enumerated constant adOpenStatic */
	public static CursorTypeEnum adOpenStatic = new CursorTypeEnum(3);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected CursorTypeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof CursorTypeEnum && __obj != null && ((CursorTypeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static CursorTypeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adOpenUnspecified;
			case 0: return adOpenForwardOnly;
			case 1: return adOpenKeyset;
			case 2: return adOpenDynamic;
			case 3: return adOpenStatic;
		}
		return new CursorTypeEnum(__n);
	}
}

