// File: DataTypeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** DataTypeEnum enumerated type */
public class DataTypeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adEmpty */
	public static DataTypeEnum adEmpty = new DataTypeEnum(0);

	/** enumerated constant adTinyInt */
	public static DataTypeEnum adTinyInt = new DataTypeEnum(16);

	/** enumerated constant adSmallInt */
	public static DataTypeEnum adSmallInt = new DataTypeEnum(2);

	/** enumerated constant adInteger */
	public static DataTypeEnum adInteger = new DataTypeEnum(3);

	/** enumerated constant adBigInt */
	public static DataTypeEnum adBigInt = new DataTypeEnum(20);

	/** enumerated constant adUnsignedTinyInt */
	public static DataTypeEnum adUnsignedTinyInt = new DataTypeEnum(17);

	/** enumerated constant adUnsignedSmallInt */
	public static DataTypeEnum adUnsignedSmallInt = new DataTypeEnum(18);

	/** enumerated constant adUnsignedInt */
	public static DataTypeEnum adUnsignedInt = new DataTypeEnum(19);

	/** enumerated constant adUnsignedBigInt */
	public static DataTypeEnum adUnsignedBigInt = new DataTypeEnum(21);

	/** enumerated constant adSingle */
	public static DataTypeEnum adSingle = new DataTypeEnum(4);

	/** enumerated constant adDouble */
	public static DataTypeEnum adDouble = new DataTypeEnum(5);

	/** enumerated constant adCurrency */
	public static DataTypeEnum adCurrency = new DataTypeEnum(6);

	/** enumerated constant adDecimal */
	public static DataTypeEnum adDecimal = new DataTypeEnum(14);

	/** enumerated constant adNumeric */
	public static DataTypeEnum adNumeric = new DataTypeEnum(131);

	/** enumerated constant adBoolean */
	public static DataTypeEnum adBoolean = new DataTypeEnum(11);

	/** enumerated constant adError */
	public static DataTypeEnum adError = new DataTypeEnum(10);

	/** enumerated constant adUserDefined */
	public static DataTypeEnum adUserDefined = new DataTypeEnum(132);

	/** enumerated constant adVariant */
	public static DataTypeEnum adVariant = new DataTypeEnum(12);

	/** enumerated constant adIDispatch */
	public static DataTypeEnum adIDispatch = new DataTypeEnum(9);

	/** enumerated constant adIUnknown */
	public static DataTypeEnum adIUnknown = new DataTypeEnum(13);

	/** enumerated constant adGUID */
	public static DataTypeEnum adGUID = new DataTypeEnum(72);

	/** enumerated constant adDate */
	public static DataTypeEnum adDate = new DataTypeEnum(7);

	/** enumerated constant adDBDate */
	public static DataTypeEnum adDBDate = new DataTypeEnum(133);

	/** enumerated constant adDBTime */
	public static DataTypeEnum adDBTime = new DataTypeEnum(134);

	/** enumerated constant adDBTimeStamp */
	public static DataTypeEnum adDBTimeStamp = new DataTypeEnum(135);

	/** enumerated constant adBSTR */
	public static DataTypeEnum adBSTR = new DataTypeEnum(8);

	/** enumerated constant adChar */
	public static DataTypeEnum adChar = new DataTypeEnum(129);

	/** enumerated constant adVarChar */
	public static DataTypeEnum adVarChar = new DataTypeEnum(200);

	/** enumerated constant adLongVarChar */
	public static DataTypeEnum adLongVarChar = new DataTypeEnum(201);

	/** enumerated constant adWChar */
	public static DataTypeEnum adWChar = new DataTypeEnum(130);

	/** enumerated constant adVarWChar */
	public static DataTypeEnum adVarWChar = new DataTypeEnum(202);

	/** enumerated constant adLongVarWChar */
	public static DataTypeEnum adLongVarWChar = new DataTypeEnum(203);

	/** enumerated constant adBinary */
	public static DataTypeEnum adBinary = new DataTypeEnum(128);

	/** enumerated constant adVarBinary */
	public static DataTypeEnum adVarBinary = new DataTypeEnum(204);

	/** enumerated constant adLongVarBinary */
	public static DataTypeEnum adLongVarBinary = new DataTypeEnum(205);

	/** enumerated constant adChapter */
	public static DataTypeEnum adChapter = new DataTypeEnum(136);

	/** enumerated constant adFileTime */
	public static DataTypeEnum adFileTime = new DataTypeEnum(64);

	/** enumerated constant adPropVariant */
	public static DataTypeEnum adPropVariant = new DataTypeEnum(138);

	/** enumerated constant adVarNumeric */
	public static DataTypeEnum adVarNumeric = new DataTypeEnum(139);

	/** enumerated constant adArray */
	public static DataTypeEnum adArray = new DataTypeEnum(8192);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected DataTypeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof DataTypeEnum && __obj != null && ((DataTypeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static DataTypeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adEmpty;
			case 16: return adTinyInt;
			case 2: return adSmallInt;
			case 3: return adInteger;
			case 20: return adBigInt;
			case 17: return adUnsignedTinyInt;
			case 18: return adUnsignedSmallInt;
			case 19: return adUnsignedInt;
			case 21: return adUnsignedBigInt;
			case 4: return adSingle;
			case 5: return adDouble;
			case 6: return adCurrency;
			case 14: return adDecimal;
			case 131: return adNumeric;
			case 11: return adBoolean;
			case 10: return adError;
			case 132: return adUserDefined;
			case 12: return adVariant;
			case 9: return adIDispatch;
			case 13: return adIUnknown;
			case 72: return adGUID;
			case 7: return adDate;
			case 133: return adDBDate;
			case 134: return adDBTime;
			case 135: return adDBTimeStamp;
			case 8: return adBSTR;
			case 129: return adChar;
			case 200: return adVarChar;
			case 201: return adLongVarChar;
			case 130: return adWChar;
			case 202: return adVarWChar;
			case 203: return adLongVarWChar;
			case 128: return adBinary;
			case 204: return adVarBinary;
			case 205: return adLongVarBinary;
			case 136: return adChapter;
			case 64: return adFileTime;
			case 138: return adPropVariant;
			case 139: return adVarNumeric;
			case 8192: return adArray;
		}
		return new DataTypeEnum(__n);
	}
}

