// File: EditModeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** EditModeEnum enumerated type */
public class EditModeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adEditNone */
	public static EditModeEnum adEditNone = new EditModeEnum(0);

	/** enumerated constant adEditInProgress */
	public static EditModeEnum adEditInProgress = new EditModeEnum(1);

	/** enumerated constant adEditAdd */
	public static EditModeEnum adEditAdd = new EditModeEnum(2);

	/** enumerated constant adEditDelete */
	public static EditModeEnum adEditDelete = new EditModeEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected EditModeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof EditModeEnum && __obj != null && ((EditModeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static EditModeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adEditNone;
			case 1: return adEditInProgress;
			case 2: return adEditAdd;
			case 4: return adEditDelete;
		}
		return new EditModeEnum(__n);
	}
}

