// File: Error.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class Error extends ezjcom.JComObject {

	public native int getNumber() throws ezjcom.JComException;

	public native String getSource() throws ezjcom.JComException;

	public native String getDescription() throws ezjcom.JComException;

	public native String getHelpFile() throws ezjcom.JComException;

	public native int getHelpContext() throws ezjcom.JComException;

	public native String getSQLState() throws ezjcom.JComException;

	public native int getNativeError() throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private Error() {}
	private Error( java.lang.ref.Reference ref ) {}

	private Error( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"Error\"" );
	}

	/** Use this method only for creating a COM interface of type Error
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static Error _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new Error(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

