// File: ErrorValueEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ErrorValueEnum enumerated type */
public class ErrorValueEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adErrProviderFailed */
	public static ErrorValueEnum adErrProviderFailed = new ErrorValueEnum(3000);

	/** enumerated constant adErrInvalidArgument */
	public static ErrorValueEnum adErrInvalidArgument = new ErrorValueEnum(3001);

	/** enumerated constant adErrOpeningFile */
	public static ErrorValueEnum adErrOpeningFile = new ErrorValueEnum(3002);

	/** enumerated constant adErrReadFile */
	public static ErrorValueEnum adErrReadFile = new ErrorValueEnum(3003);

	/** enumerated constant adErrWriteFile */
	public static ErrorValueEnum adErrWriteFile = new ErrorValueEnum(3004);

	/** enumerated constant adErrNoCurrentRecord */
	public static ErrorValueEnum adErrNoCurrentRecord = new ErrorValueEnum(3021);

	/** enumerated constant adErrIllegalOperation */
	public static ErrorValueEnum adErrIllegalOperation = new ErrorValueEnum(3219);

	/** enumerated constant adErrCantChangeProvider */
	public static ErrorValueEnum adErrCantChangeProvider = new ErrorValueEnum(3220);

	/** enumerated constant adErrInTransaction */
	public static ErrorValueEnum adErrInTransaction = new ErrorValueEnum(3246);

	/** enumerated constant adErrFeatureNotAvailable */
	public static ErrorValueEnum adErrFeatureNotAvailable = new ErrorValueEnum(3251);

	/** enumerated constant adErrItemNotFound */
	public static ErrorValueEnum adErrItemNotFound = new ErrorValueEnum(3265);

	/** enumerated constant adErrObjectInCollection */
	public static ErrorValueEnum adErrObjectInCollection = new ErrorValueEnum(3367);

	/** enumerated constant adErrObjectNotSet */
	public static ErrorValueEnum adErrObjectNotSet = new ErrorValueEnum(3420);

	/** enumerated constant adErrDataConversion */
	public static ErrorValueEnum adErrDataConversion = new ErrorValueEnum(3421);

	/** enumerated constant adErrObjectClosed */
	public static ErrorValueEnum adErrObjectClosed = new ErrorValueEnum(3704);

	/** enumerated constant adErrObjectOpen */
	public static ErrorValueEnum adErrObjectOpen = new ErrorValueEnum(3705);

	/** enumerated constant adErrProviderNotFound */
	public static ErrorValueEnum adErrProviderNotFound = new ErrorValueEnum(3706);

	/** enumerated constant adErrBoundToCommand */
	public static ErrorValueEnum adErrBoundToCommand = new ErrorValueEnum(3707);

	/** enumerated constant adErrInvalidParamInfo */
	public static ErrorValueEnum adErrInvalidParamInfo = new ErrorValueEnum(3708);

	/** enumerated constant adErrInvalidConnection */
	public static ErrorValueEnum adErrInvalidConnection = new ErrorValueEnum(3709);

	/** enumerated constant adErrNotReentrant */
	public static ErrorValueEnum adErrNotReentrant = new ErrorValueEnum(3710);

	/** enumerated constant adErrStillExecuting */
	public static ErrorValueEnum adErrStillExecuting = new ErrorValueEnum(3711);

	/** enumerated constant adErrOperationCancelled */
	public static ErrorValueEnum adErrOperationCancelled = new ErrorValueEnum(3712);

	/** enumerated constant adErrStillConnecting */
	public static ErrorValueEnum adErrStillConnecting = new ErrorValueEnum(3713);

	/** enumerated constant adErrInvalidTransaction */
	public static ErrorValueEnum adErrInvalidTransaction = new ErrorValueEnum(3714);

	/** enumerated constant adErrNotExecuting */
	public static ErrorValueEnum adErrNotExecuting = new ErrorValueEnum(3715);

	/** enumerated constant adErrUnsafeOperation */
	public static ErrorValueEnum adErrUnsafeOperation = new ErrorValueEnum(3716);

	/** enumerated constant adwrnSecurityDialog */
	public static ErrorValueEnum adwrnSecurityDialog = new ErrorValueEnum(3717);

	/** enumerated constant adwrnSecurityDialogHeader */
	public static ErrorValueEnum adwrnSecurityDialogHeader = new ErrorValueEnum(3718);

	/** enumerated constant adErrIntegrityViolation */
	public static ErrorValueEnum adErrIntegrityViolation = new ErrorValueEnum(3719);

	/** enumerated constant adErrPermissionDenied */
	public static ErrorValueEnum adErrPermissionDenied = new ErrorValueEnum(3720);

	/** enumerated constant adErrDataOverflow */
	public static ErrorValueEnum adErrDataOverflow = new ErrorValueEnum(3721);

	/** enumerated constant adErrSchemaViolation */
	public static ErrorValueEnum adErrSchemaViolation = new ErrorValueEnum(3722);

	/** enumerated constant adErrSignMismatch */
	public static ErrorValueEnum adErrSignMismatch = new ErrorValueEnum(3723);

	/** enumerated constant adErrCantConvertvalue */
	public static ErrorValueEnum adErrCantConvertvalue = new ErrorValueEnum(3724);

	/** enumerated constant adErrCantCreate */
	public static ErrorValueEnum adErrCantCreate = new ErrorValueEnum(3725);

	/** enumerated constant adErrColumnNotOnThisRow */
	public static ErrorValueEnum adErrColumnNotOnThisRow = new ErrorValueEnum(3726);

	/** enumerated constant adErrURLDoesNotExist */
	public static ErrorValueEnum adErrURLDoesNotExist = new ErrorValueEnum(3727);

	/** enumerated constant adErrTreePermissionDenied */
	public static ErrorValueEnum adErrTreePermissionDenied = new ErrorValueEnum(3728);

	/** enumerated constant adErrInvalidURL */
	public static ErrorValueEnum adErrInvalidURL = new ErrorValueEnum(3729);

	/** enumerated constant adErrResourceLocked */
	public static ErrorValueEnum adErrResourceLocked = new ErrorValueEnum(3730);

	/** enumerated constant adErrResourceExists */
	public static ErrorValueEnum adErrResourceExists = new ErrorValueEnum(3731);

	/** enumerated constant adErrCannotComplete */
	public static ErrorValueEnum adErrCannotComplete = new ErrorValueEnum(3732);

	/** enumerated constant adErrVolumeNotFound */
	public static ErrorValueEnum adErrVolumeNotFound = new ErrorValueEnum(3733);

	/** enumerated constant adErrOutOfSpace */
	public static ErrorValueEnum adErrOutOfSpace = new ErrorValueEnum(3734);

	/** enumerated constant adErrResourceOutOfScope */
	public static ErrorValueEnum adErrResourceOutOfScope = new ErrorValueEnum(3735);

	/** enumerated constant adErrUnavailable */
	public static ErrorValueEnum adErrUnavailable = new ErrorValueEnum(3736);

	/** enumerated constant adErrURLNamedRowDoesNotExist */
	public static ErrorValueEnum adErrURLNamedRowDoesNotExist = new ErrorValueEnum(3737);

	/** enumerated constant adErrDelResOutOfScope */
	public static ErrorValueEnum adErrDelResOutOfScope = new ErrorValueEnum(3738);

	/** enumerated constant adErrPropInvalidColumn */
	public static ErrorValueEnum adErrPropInvalidColumn = new ErrorValueEnum(3739);

	/** enumerated constant adErrPropInvalidOption */
	public static ErrorValueEnum adErrPropInvalidOption = new ErrorValueEnum(3740);

	/** enumerated constant adErrPropInvalidValue */
	public static ErrorValueEnum adErrPropInvalidValue = new ErrorValueEnum(3741);

	/** enumerated constant adErrPropConflicting */
	public static ErrorValueEnum adErrPropConflicting = new ErrorValueEnum(3742);

	/** enumerated constant adErrPropNotAllSettable */
	public static ErrorValueEnum adErrPropNotAllSettable = new ErrorValueEnum(3743);

	/** enumerated constant adErrPropNotSet */
	public static ErrorValueEnum adErrPropNotSet = new ErrorValueEnum(3744);

	/** enumerated constant adErrPropNotSettable */
	public static ErrorValueEnum adErrPropNotSettable = new ErrorValueEnum(3745);

	/** enumerated constant adErrPropNotSupported */
	public static ErrorValueEnum adErrPropNotSupported = new ErrorValueEnum(3746);

	/** enumerated constant adErrCatalogNotSet */
	public static ErrorValueEnum adErrCatalogNotSet = new ErrorValueEnum(3747);

	/** enumerated constant adErrCantChangeConnection */
	public static ErrorValueEnum adErrCantChangeConnection = new ErrorValueEnum(3748);

	/** enumerated constant adErrFieldsUpdateFailed */
	public static ErrorValueEnum adErrFieldsUpdateFailed = new ErrorValueEnum(3749);

	/** enumerated constant adErrDenyNotSupported */
	public static ErrorValueEnum adErrDenyNotSupported = new ErrorValueEnum(3750);

	/** enumerated constant adErrDenyTypeNotSupported */
	public static ErrorValueEnum adErrDenyTypeNotSupported = new ErrorValueEnum(3751);

	/** enumerated constant adErrProviderNotSpecified */
	public static ErrorValueEnum adErrProviderNotSpecified = new ErrorValueEnum(3753);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ErrorValueEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ErrorValueEnum && __obj != null && ((ErrorValueEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ErrorValueEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 3000: return adErrProviderFailed;
			case 3001: return adErrInvalidArgument;
			case 3002: return adErrOpeningFile;
			case 3003: return adErrReadFile;
			case 3004: return adErrWriteFile;
			case 3021: return adErrNoCurrentRecord;
			case 3219: return adErrIllegalOperation;
			case 3220: return adErrCantChangeProvider;
			case 3246: return adErrInTransaction;
			case 3251: return adErrFeatureNotAvailable;
			case 3265: return adErrItemNotFound;
			case 3367: return adErrObjectInCollection;
			case 3420: return adErrObjectNotSet;
			case 3421: return adErrDataConversion;
			case 3704: return adErrObjectClosed;
			case 3705: return adErrObjectOpen;
			case 3706: return adErrProviderNotFound;
			case 3707: return adErrBoundToCommand;
			case 3708: return adErrInvalidParamInfo;
			case 3709: return adErrInvalidConnection;
			case 3710: return adErrNotReentrant;
			case 3711: return adErrStillExecuting;
			case 3712: return adErrOperationCancelled;
			case 3713: return adErrStillConnecting;
			case 3714: return adErrInvalidTransaction;
			case 3715: return adErrNotExecuting;
			case 3716: return adErrUnsafeOperation;
			case 3717: return adwrnSecurityDialog;
			case 3718: return adwrnSecurityDialogHeader;
			case 3719: return adErrIntegrityViolation;
			case 3720: return adErrPermissionDenied;
			case 3721: return adErrDataOverflow;
			case 3722: return adErrSchemaViolation;
			case 3723: return adErrSignMismatch;
			case 3724: return adErrCantConvertvalue;
			case 3725: return adErrCantCreate;
			case 3726: return adErrColumnNotOnThisRow;
			case 3727: return adErrURLDoesNotExist;
			case 3728: return adErrTreePermissionDenied;
			case 3729: return adErrInvalidURL;
			case 3730: return adErrResourceLocked;
			case 3731: return adErrResourceExists;
			case 3732: return adErrCannotComplete;
			case 3733: return adErrVolumeNotFound;
			case 3734: return adErrOutOfSpace;
			case 3735: return adErrResourceOutOfScope;
			case 3736: return adErrUnavailable;
			case 3737: return adErrURLNamedRowDoesNotExist;
			case 3738: return adErrDelResOutOfScope;
			case 3739: return adErrPropInvalidColumn;
			case 3740: return adErrPropInvalidOption;
			case 3741: return adErrPropInvalidValue;
			case 3742: return adErrPropConflicting;
			case 3743: return adErrPropNotAllSettable;
			case 3744: return adErrPropNotSet;
			case 3745: return adErrPropNotSettable;
			case 3746: return adErrPropNotSupported;
			case 3747: return adErrCatalogNotSet;
			case 3748: return adErrCantChangeConnection;
			case 3749: return adErrFieldsUpdateFailed;
			case 3750: return adErrDenyNotSupported;
			case 3751: return adErrDenyTypeNotSupported;
			case 3753: return adErrProviderNotSpecified;
		}
		return new ErrorValueEnum(__n);
	}
}

