// File: EventStatusEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** EventStatusEnum enumerated type */
public class EventStatusEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adStatusOK */
	public static EventStatusEnum adStatusOK = new EventStatusEnum(1);

	/** enumerated constant adStatusErrorsOccurred */
	public static EventStatusEnum adStatusErrorsOccurred = new EventStatusEnum(2);

	/** enumerated constant adStatusCantDeny */
	public static EventStatusEnum adStatusCantDeny = new EventStatusEnum(3);

	/** enumerated constant adStatusCancel */
	public static EventStatusEnum adStatusCancel = new EventStatusEnum(4);

	/** enumerated constant adStatusUnwantedEvent */
	public static EventStatusEnum adStatusUnwantedEvent = new EventStatusEnum(5);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected EventStatusEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof EventStatusEnum && __obj != null && ((EventStatusEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static EventStatusEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adStatusOK;
			case 2: return adStatusErrorsOccurred;
			case 3: return adStatusCantDeny;
			case 4: return adStatusCancel;
			case 5: return adStatusUnwantedEvent;
		}
		return new EventStatusEnum(__n);
	}
}

