// File: ExecuteOptionEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ExecuteOptionEnum enumerated type */
public class ExecuteOptionEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adOptionUnspecified */
	public static ExecuteOptionEnum adOptionUnspecified = new ExecuteOptionEnum(-1);

	/** enumerated constant adAsyncExecute */
	public static ExecuteOptionEnum adAsyncExecute = new ExecuteOptionEnum(16);

	/** enumerated constant adAsyncFetch */
	public static ExecuteOptionEnum adAsyncFetch = new ExecuteOptionEnum(32);

	/** enumerated constant adAsyncFetchNonBlocking */
	public static ExecuteOptionEnum adAsyncFetchNonBlocking = new ExecuteOptionEnum(64);

	/** enumerated constant adExecuteNoRecords */
	public static ExecuteOptionEnum adExecuteNoRecords = new ExecuteOptionEnum(128);

	/** enumerated constant adExecuteStream */
	public static ExecuteOptionEnum adExecuteStream = new ExecuteOptionEnum(1024);

	/** enumerated constant adExecuteRecord */
	public static ExecuteOptionEnum adExecuteRecord = new ExecuteOptionEnum(2048);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ExecuteOptionEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ExecuteOptionEnum && __obj != null && ((ExecuteOptionEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ExecuteOptionEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adOptionUnspecified;
			case 16: return adAsyncExecute;
			case 32: return adAsyncFetch;
			case 64: return adAsyncFetchNonBlocking;
			case 128: return adExecuteNoRecords;
			case 1024: return adExecuteStream;
			case 2048: return adExecuteRecord;
		}
		return new ExecuteOptionEnum(__n);
	}
}

