// File: Fields.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class Fields extends ezjcom.JComObject {

	public native int getCount() throws ezjcom.JComException;

	public native void Refresh() throws ezjcom.JComException;

	public native SMS.Field getItem(ezjcom.JComVariant Index) throws ezjcom.JComException;

	public native void _Append(String Name, SMS.DataTypeEnum Type, int DefinedSize, SMS.FieldAttributeEnum Attrib) throws ezjcom.JComException;

	public native void Delete(ezjcom.JComVariant Index) throws ezjcom.JComException;

	public native void Append(String Name, SMS.DataTypeEnum Type, int DefinedSize, SMS.FieldAttributeEnum Attrib) throws ezjcom.JComException;

	public native void Append(String Name, SMS.DataTypeEnum Type, int DefinedSize, SMS.FieldAttributeEnum Attrib, ezjcom.JComVariant FieldValue) throws ezjcom.JComException;

	public native void Update() throws ezjcom.JComException;

	public native void Resync(SMS.ResyncEnum ResyncValues) throws ezjcom.JComException;

	public native void CancelUpdate() throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private Fields() {}
	private Fields( java.lang.ref.Reference ref ) {}

	private Fields( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"Fields\"" );
	}

	/** Use this method only for creating a COM interface of type Fields
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static Fields _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new Fields(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

