// File: FieldStatusEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** FieldStatusEnum enumerated type */
public class FieldStatusEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adFieldOK */
	public static FieldStatusEnum adFieldOK = new FieldStatusEnum(0);

	/** enumerated constant adFieldCantConvertValue */
	public static FieldStatusEnum adFieldCantConvertValue = new FieldStatusEnum(2);

	/** enumerated constant adFieldIsNull */
	public static FieldStatusEnum adFieldIsNull = new FieldStatusEnum(3);

	/** enumerated constant adFieldTruncated */
	public static FieldStatusEnum adFieldTruncated = new FieldStatusEnum(4);

	/** enumerated constant adFieldSignMismatch */
	public static FieldStatusEnum adFieldSignMismatch = new FieldStatusEnum(5);

	/** enumerated constant adFieldDataOverflow */
	public static FieldStatusEnum adFieldDataOverflow = new FieldStatusEnum(6);

	/** enumerated constant adFieldCantCreate */
	public static FieldStatusEnum adFieldCantCreate = new FieldStatusEnum(7);

	/** enumerated constant adFieldUnavailable */
	public static FieldStatusEnum adFieldUnavailable = new FieldStatusEnum(8);

	/** enumerated constant adFieldPermissionDenied */
	public static FieldStatusEnum adFieldPermissionDenied = new FieldStatusEnum(9);

	/** enumerated constant adFieldIntegrityViolation */
	public static FieldStatusEnum adFieldIntegrityViolation = new FieldStatusEnum(10);

	/** enumerated constant adFieldSchemaViolation */
	public static FieldStatusEnum adFieldSchemaViolation = new FieldStatusEnum(11);

	/** enumerated constant adFieldBadStatus */
	public static FieldStatusEnum adFieldBadStatus = new FieldStatusEnum(12);

	/** enumerated constant adFieldDefault */
	public static FieldStatusEnum adFieldDefault = new FieldStatusEnum(13);

	/** enumerated constant adFieldIgnore */
	public static FieldStatusEnum adFieldIgnore = new FieldStatusEnum(15);

	/** enumerated constant adFieldDoesNotExist */
	public static FieldStatusEnum adFieldDoesNotExist = new FieldStatusEnum(16);

	/** enumerated constant adFieldInvalidURL */
	public static FieldStatusEnum adFieldInvalidURL = new FieldStatusEnum(17);

	/** enumerated constant adFieldResourceLocked */
	public static FieldStatusEnum adFieldResourceLocked = new FieldStatusEnum(18);

	/** enumerated constant adFieldResourceExists */
	public static FieldStatusEnum adFieldResourceExists = new FieldStatusEnum(19);

	/** enumerated constant adFieldCannotComplete */
	public static FieldStatusEnum adFieldCannotComplete = new FieldStatusEnum(20);

	/** enumerated constant adFieldVolumeNotFound */
	public static FieldStatusEnum adFieldVolumeNotFound = new FieldStatusEnum(21);

	/** enumerated constant adFieldOutOfSpace */
	public static FieldStatusEnum adFieldOutOfSpace = new FieldStatusEnum(22);

	/** enumerated constant adFieldCannotDeleteSource */
	public static FieldStatusEnum adFieldCannotDeleteSource = new FieldStatusEnum(23);

	/** enumerated constant adFieldReadOnly */
	public static FieldStatusEnum adFieldReadOnly = new FieldStatusEnum(24);

	/** enumerated constant adFieldResourceOutOfScope */
	public static FieldStatusEnum adFieldResourceOutOfScope = new FieldStatusEnum(25);

	/** enumerated constant adFieldAlreadyExists */
	public static FieldStatusEnum adFieldAlreadyExists = new FieldStatusEnum(26);

	/** enumerated constant adFieldPendingInsert */
	public static FieldStatusEnum adFieldPendingInsert = new FieldStatusEnum(65536);

	/** enumerated constant adFieldPendingDelete */
	public static FieldStatusEnum adFieldPendingDelete = new FieldStatusEnum(131072);

	/** enumerated constant adFieldPendingChange */
	public static FieldStatusEnum adFieldPendingChange = new FieldStatusEnum(262144);

	/** enumerated constant adFieldPendingUnknown */
	public static FieldStatusEnum adFieldPendingUnknown = new FieldStatusEnum(524288);

	/** enumerated constant adFieldPendingUnknownDelete */
	public static FieldStatusEnum adFieldPendingUnknownDelete = new FieldStatusEnum(1048576);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected FieldStatusEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof FieldStatusEnum && __obj != null && ((FieldStatusEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static FieldStatusEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adFieldOK;
			case 2: return adFieldCantConvertValue;
			case 3: return adFieldIsNull;
			case 4: return adFieldTruncated;
			case 5: return adFieldSignMismatch;
			case 6: return adFieldDataOverflow;
			case 7: return adFieldCantCreate;
			case 8: return adFieldUnavailable;
			case 9: return adFieldPermissionDenied;
			case 10: return adFieldIntegrityViolation;
			case 11: return adFieldSchemaViolation;
			case 12: return adFieldBadStatus;
			case 13: return adFieldDefault;
			case 15: return adFieldIgnore;
			case 16: return adFieldDoesNotExist;
			case 17: return adFieldInvalidURL;
			case 18: return adFieldResourceLocked;
			case 19: return adFieldResourceExists;
			case 20: return adFieldCannotComplete;
			case 21: return adFieldVolumeNotFound;
			case 22: return adFieldOutOfSpace;
			case 23: return adFieldCannotDeleteSource;
			case 24: return adFieldReadOnly;
			case 25: return adFieldResourceOutOfScope;
			case 26: return adFieldAlreadyExists;
			case 65536: return adFieldPendingInsert;
			case 131072: return adFieldPendingDelete;
			case 262144: return adFieldPendingChange;
			case 524288: return adFieldPendingUnknown;
			case 1048576: return adFieldPendingUnknownDelete;
		}
		return new FieldStatusEnum(__n);
	}
}

