// File: FieldEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** FieldEnum enumerated type */
public class FieldEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adDefaultStream */
	public static FieldEnum adDefaultStream = new FieldEnum(-1);

	/** enumerated constant adRecordURL */
	public static FieldEnum adRecordURL = new FieldEnum(-2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected FieldEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof FieldEnum && __obj != null && ((FieldEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static FieldEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adDefaultStream;
			case -2: return adRecordURL;
		}
		return new FieldEnum(__n);
	}
}

