// File: FieldAttributeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** FieldAttributeEnum enumerated type */
public class FieldAttributeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adFldUnspecified */
	public static FieldAttributeEnum adFldUnspecified = new FieldAttributeEnum(-1);

	/** enumerated constant adFldMayDefer */
	public static FieldAttributeEnum adFldMayDefer = new FieldAttributeEnum(2);

	/** enumerated constant adFldUpdatable */
	public static FieldAttributeEnum adFldUpdatable = new FieldAttributeEnum(4);

	/** enumerated constant adFldUnknownUpdatable */
	public static FieldAttributeEnum adFldUnknownUpdatable = new FieldAttributeEnum(8);

	/** enumerated constant adFldFixed */
	public static FieldAttributeEnum adFldFixed = new FieldAttributeEnum(16);

	/** enumerated constant adFldIsNullable */
	public static FieldAttributeEnum adFldIsNullable = new FieldAttributeEnum(32);

	/** enumerated constant adFldMayBeNull */
	public static FieldAttributeEnum adFldMayBeNull = new FieldAttributeEnum(64);

	/** enumerated constant adFldLong */
	public static FieldAttributeEnum adFldLong = new FieldAttributeEnum(128);

	/** enumerated constant adFldRowID */
	public static FieldAttributeEnum adFldRowID = new FieldAttributeEnum(256);

	/** enumerated constant adFldRowVersion */
	public static FieldAttributeEnum adFldRowVersion = new FieldAttributeEnum(512);

	/** enumerated constant adFldCacheDeferred */
	public static FieldAttributeEnum adFldCacheDeferred = new FieldAttributeEnum(4096);

	/** enumerated constant adFldIsChapter */
	public static FieldAttributeEnum adFldIsChapter = new FieldAttributeEnum(8192);

	/** enumerated constant adFldNegativeScale */
	public static FieldAttributeEnum adFldNegativeScale = new FieldAttributeEnum(16384);

	/** enumerated constant adFldKeyColumn */
	public static FieldAttributeEnum adFldKeyColumn = new FieldAttributeEnum(32768);

	/** enumerated constant adFldIsRowURL */
	public static FieldAttributeEnum adFldIsRowURL = new FieldAttributeEnum(65536);

	/** enumerated constant adFldIsDefaultStream */
	public static FieldAttributeEnum adFldIsDefaultStream = new FieldAttributeEnum(131072);

	/** enumerated constant adFldIsCollection */
	public static FieldAttributeEnum adFldIsCollection = new FieldAttributeEnum(262144);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected FieldAttributeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof FieldAttributeEnum && __obj != null && ((FieldAttributeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static FieldAttributeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adFldUnspecified;
			case 2: return adFldMayDefer;
			case 4: return adFldUpdatable;
			case 8: return adFldUnknownUpdatable;
			case 16: return adFldFixed;
			case 32: return adFldIsNullable;
			case 64: return adFldMayBeNull;
			case 128: return adFldLong;
			case 256: return adFldRowID;
			case 512: return adFldRowVersion;
			case 4096: return adFldCacheDeferred;
			case 8192: return adFldIsChapter;
			case 16384: return adFldNegativeScale;
			case 32768: return adFldKeyColumn;
			case 65536: return adFldIsRowURL;
			case 131072: return adFldIsDefaultStream;
			case 262144: return adFldIsCollection;
		}
		return new FieldAttributeEnum(__n);
	}
}

