// File: FilterGroupEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** FilterGroupEnum enumerated type */
public class FilterGroupEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adFilterNone */
	public static FilterGroupEnum adFilterNone = new FilterGroupEnum(0);

	/** enumerated constant adFilterPendingRecords */
	public static FilterGroupEnum adFilterPendingRecords = new FilterGroupEnum(1);

	/** enumerated constant adFilterAffectedRecords */
	public static FilterGroupEnum adFilterAffectedRecords = new FilterGroupEnum(2);

	/** enumerated constant adFilterFetchedRecords */
	public static FilterGroupEnum adFilterFetchedRecords = new FilterGroupEnum(3);

	/** enumerated constant adFilterPredicate */
	public static FilterGroupEnum adFilterPredicate = new FilterGroupEnum(4);

	/** enumerated constant adFilterConflictingRecords */
	public static FilterGroupEnum adFilterConflictingRecords = new FilterGroupEnum(5);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected FilterGroupEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof FilterGroupEnum && __obj != null && ((FilterGroupEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static FilterGroupEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adFilterNone;
			case 1: return adFilterPendingRecords;
			case 2: return adFilterAffectedRecords;
			case 3: return adFilterFetchedRecords;
			case 4: return adFilterPredicate;
			case 5: return adFilterConflictingRecords;
		}
		return new FilterGroupEnum(__n);
	}
}

