// File: GetRowsOptionEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** GetRowsOptionEnum enumerated type */
public class GetRowsOptionEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adGetRowsRest */
	public static GetRowsOptionEnum adGetRowsRest = new GetRowsOptionEnum(-1);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected GetRowsOptionEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof GetRowsOptionEnum && __obj != null && ((GetRowsOptionEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static GetRowsOptionEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adGetRowsRest;
		}
		return new GetRowsOptionEnum(__n);
	}
}

