// File: IsolationLevelEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** IsolationLevelEnum enumerated type */
public class IsolationLevelEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adXactUnspecified */
	public static IsolationLevelEnum adXactUnspecified = new IsolationLevelEnum(-1);

	/** enumerated constant adXactChaos */
	public static IsolationLevelEnum adXactChaos = new IsolationLevelEnum(16);

	/** enumerated constant adXactReadUncommitted */
	public static IsolationLevelEnum adXactReadUncommitted = new IsolationLevelEnum(256);

	/** enumerated constant adXactBrowse */
	public static IsolationLevelEnum adXactBrowse = new IsolationLevelEnum(256);

	/** enumerated constant adXactCursorStability */
	public static IsolationLevelEnum adXactCursorStability = new IsolationLevelEnum(4096);

	/** enumerated constant adXactReadCommitted */
	public static IsolationLevelEnum adXactReadCommitted = new IsolationLevelEnum(4096);

	/** enumerated constant adXactRepeatableRead */
	public static IsolationLevelEnum adXactRepeatableRead = new IsolationLevelEnum(65536);

	/** enumerated constant adXactSerializable */
	public static IsolationLevelEnum adXactSerializable = new IsolationLevelEnum(1048576);

	/** enumerated constant adXactIsolated */
	public static IsolationLevelEnum adXactIsolated = new IsolationLevelEnum(1048576);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected IsolationLevelEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof IsolationLevelEnum && __obj != null && ((IsolationLevelEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static IsolationLevelEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adXactUnspecified;
			case 16: return adXactChaos;
			case 256: return adXactReadUncommitted;
			// ** Duplicate ** case 256: return adXactBrowse;
			case 4096: return adXactCursorStability;
			// ** Duplicate ** case 4096: return adXactReadCommitted;
			case 65536: return adXactRepeatableRead;
			case 1048576: return adXactSerializable;
			// ** Duplicate ** case 1048576: return adXactIsolated;
		}
		return new IsolationLevelEnum(__n);
	}
}

