// File: KCM_SMS.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

public class KCM_SMS extends ezjcom.JComActiveXObject {

	// Available COM interface objects.
	//

	/** Retrieve the COM Interface "_KCM_SMS" */
	public _KCM_SMS get_KCM_SMS() throws ezjcom.JComException {
		if ( _intf_KCM_SMS == null ) throw new ezjcom.JComException( "Interface not supported by COM object.  Check for version mismatch.  If version is OK, on \"Advanced\" page select \"Object Creation\"" );
		return _intf_KCM_SMS;
	}


	/** Add event listener "__KCM_SMS" */
	public void addJComEventListener( __KCM_SMS listener ) throws ezjcom.JComException { _JComAddEventListener( listener ); }

	/** Remove event listener "__KCM_SMS" */
	public void removeJComEventListener( __KCM_SMS listener ) throws ezjcom.JComException { _JComRemoveEventListener( listener ); }



	// Constructor(s)
	/** Default ActiveX object constructor.  <B>WARNING: This object is described as <I>non-creatable</I>, construction may not succeed</b>. */
	public KCM_SMS() throws ezjcom.JComException
	{
		this( false, false );
	}

	/** Alternate constructor.
	  * Try to find existing ActiveX object, or create using Server-only options.
	  * <P>Finding existing objects is not supported by many COM/ActiveX objects,
	  *  but EZ-JCom includes support for those COM/ActiveX objects that can be found.
	  *  <P>Creating using server-only options (first argument must be false) is useful
	  *  for some MS Office products.

	  * <B>WARNING: This object is described as <I>non-creatable</I>, construction may not succeed</b>.
	  */
	public KCM_SMS( boolean find, boolean createAsServer ) throws ezjcom.JComException
	{
		if ( ! __JComCreateObject( find, createAsServer ))
			throw new ezjcom.JComException( "Object creation failed for COM object \"KCM_SMS\"" );
		__JComInitialize();
	}

	private native Object __JComNewObj( Class cls );

	/** Initializer.  Used internally by EZ JCom. */
	private void __JComInitialize() throws ezjcom.JComException
	{
		_intf_KCM_SMS = (_KCM_SMS) __JComNewObj( _KCM_SMS.class );
		if ( ! _intf_KCM_SMS.__JComLoad( this, true ))
			_intf_KCM_SMS = null;
	}

	// Constuctor for internal EZ JCom Usage only
	private KCM_SMS( java.lang.ref.Reference ref ) {}

	/** Set container for this activeX object. */
	public void setActiveXContainer( ezjcom.JComActiveXContainer ezjActiveXContainer) throws ezjcom.JComException
	{
		ezjActiveXContainer.setActiveX( this );
	}

	/* JNI function used internally by EZ-JCom */
	private native boolean __JComCreateObject( boolean find, boolean createAsServer ) throws ezjcom.JComException;
	private static native String __JComGetGUID();
	private native Object[] __RemoteEventAdd( String interfaceStr );

	_KCM_SMS _intf_KCM_SMS;

	static {
		System.loadLibrary( "JKCMSMS" );
	}

}
