// File: LockTypeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** LockTypeEnum enumerated type */
public class LockTypeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adLockUnspecified */
	public static LockTypeEnum adLockUnspecified = new LockTypeEnum(-1);

	/** enumerated constant adLockReadOnly */
	public static LockTypeEnum adLockReadOnly = new LockTypeEnum(1);

	/** enumerated constant adLockPessimistic */
	public static LockTypeEnum adLockPessimistic = new LockTypeEnum(2);

	/** enumerated constant adLockOptimistic */
	public static LockTypeEnum adLockOptimistic = new LockTypeEnum(3);

	/** enumerated constant adLockBatchOptimistic */
	public static LockTypeEnum adLockBatchOptimistic = new LockTypeEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected LockTypeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof LockTypeEnum && __obj != null && ((LockTypeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static LockTypeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adLockUnspecified;
			case 1: return adLockReadOnly;
			case 2: return adLockPessimistic;
			case 3: return adLockOptimistic;
			case 4: return adLockBatchOptimistic;
		}
		return new LockTypeEnum(__n);
	}
}

