// File: MarshalOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** MarshalOptionsEnum enumerated type */
public class MarshalOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adMarshalAll */
	public static MarshalOptionsEnum adMarshalAll = new MarshalOptionsEnum(0);

	/** enumerated constant adMarshalModifiedOnly */
	public static MarshalOptionsEnum adMarshalModifiedOnly = new MarshalOptionsEnum(1);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected MarshalOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof MarshalOptionsEnum && __obj != null && ((MarshalOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static MarshalOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adMarshalAll;
			case 1: return adMarshalModifiedOnly;
		}
		return new MarshalOptionsEnum(__n);
	}
}

