// File: MoveRecordOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** MoveRecordOptionsEnum enumerated type */
public class MoveRecordOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adMoveUnspecified */
	public static MoveRecordOptionsEnum adMoveUnspecified = new MoveRecordOptionsEnum(-1);

	/** enumerated constant adMoveOverWrite */
	public static MoveRecordOptionsEnum adMoveOverWrite = new MoveRecordOptionsEnum(1);

	/** enumerated constant adMoveDontUpdateLinks */
	public static MoveRecordOptionsEnum adMoveDontUpdateLinks = new MoveRecordOptionsEnum(2);

	/** enumerated constant adMoveAllowEmulation */
	public static MoveRecordOptionsEnum adMoveAllowEmulation = new MoveRecordOptionsEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected MoveRecordOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof MoveRecordOptionsEnum && __obj != null && ((MoveRecordOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static MoveRecordOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adMoveUnspecified;
			case 1: return adMoveOverWrite;
			case 2: return adMoveDontUpdateLinks;
			case 4: return adMoveAllowEmulation;
		}
		return new MoveRecordOptionsEnum(__n);
	}
}

