// File: ObjectStateEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ObjectStateEnum enumerated type */
public class ObjectStateEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adStateClosed */
	public static ObjectStateEnum adStateClosed = new ObjectStateEnum(0);

	/** enumerated constant adStateOpen */
	public static ObjectStateEnum adStateOpen = new ObjectStateEnum(1);

	/** enumerated constant adStateConnecting */
	public static ObjectStateEnum adStateConnecting = new ObjectStateEnum(2);

	/** enumerated constant adStateExecuting */
	public static ObjectStateEnum adStateExecuting = new ObjectStateEnum(4);

	/** enumerated constant adStateFetching */
	public static ObjectStateEnum adStateFetching = new ObjectStateEnum(8);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ObjectStateEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ObjectStateEnum && __obj != null && ((ObjectStateEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ObjectStateEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adStateClosed;
			case 1: return adStateOpen;
			case 2: return adStateConnecting;
			case 4: return adStateExecuting;
			case 8: return adStateFetching;
		}
		return new ObjectStateEnum(__n);
	}
}

