// File: ParameterDirectionEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ParameterDirectionEnum enumerated type */
public class ParameterDirectionEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adParamUnknown */
	public static ParameterDirectionEnum adParamUnknown = new ParameterDirectionEnum(0);

	/** enumerated constant adParamInput */
	public static ParameterDirectionEnum adParamInput = new ParameterDirectionEnum(1);

	/** enumerated constant adParamOutput */
	public static ParameterDirectionEnum adParamOutput = new ParameterDirectionEnum(2);

	/** enumerated constant adParamInputOutput */
	public static ParameterDirectionEnum adParamInputOutput = new ParameterDirectionEnum(3);

	/** enumerated constant adParamReturnValue */
	public static ParameterDirectionEnum adParamReturnValue = new ParameterDirectionEnum(4);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ParameterDirectionEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ParameterDirectionEnum && __obj != null && ((ParameterDirectionEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ParameterDirectionEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adParamUnknown;
			case 1: return adParamInput;
			case 2: return adParamOutput;
			case 3: return adParamInputOutput;
			case 4: return adParamReturnValue;
		}
		return new ParameterDirectionEnum(__n);
	}
}

