// File: ParameterAttributesEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ParameterAttributesEnum enumerated type */
public class ParameterAttributesEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adParamSigned */
	public static ParameterAttributesEnum adParamSigned = new ParameterAttributesEnum(16);

	/** enumerated constant adParamNullable */
	public static ParameterAttributesEnum adParamNullable = new ParameterAttributesEnum(64);

	/** enumerated constant adParamLong */
	public static ParameterAttributesEnum adParamLong = new ParameterAttributesEnum(128);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ParameterAttributesEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ParameterAttributesEnum && __obj != null && ((ParameterAttributesEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ParameterAttributesEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 16: return adParamSigned;
			case 64: return adParamNullable;
			case 128: return adParamLong;
		}
		return new ParameterAttributesEnum(__n);
	}
}

