// File: PersistFormatEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** PersistFormatEnum enumerated type */
public class PersistFormatEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adPersistADTG */
	public static PersistFormatEnum adPersistADTG = new PersistFormatEnum(0);

	/** enumerated constant adPersistXML */
	public static PersistFormatEnum adPersistXML = new PersistFormatEnum(1);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected PersistFormatEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof PersistFormatEnum && __obj != null && ((PersistFormatEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static PersistFormatEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adPersistADTG;
			case 1: return adPersistXML;
		}
		return new PersistFormatEnum(__n);
	}
}

