// File: PositionEnum_Param.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** PositionEnum_Param enumerated type */
public class PositionEnum_Param extends ezjcom.JComEnumeration {


	/** enumerated constant adPosUnknown */
	public static PositionEnum_Param adPosUnknown = new PositionEnum_Param(-1);

	/** enumerated constant adPosBOF */
	public static PositionEnum_Param adPosBOF = new PositionEnum_Param(-2);

	/** enumerated constant adPosEOF */
	public static PositionEnum_Param adPosEOF = new PositionEnum_Param(-3);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected PositionEnum_Param( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof PositionEnum_Param && __obj != null && ((PositionEnum_Param)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static PositionEnum_Param intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adPosUnknown;
			case -2: return adPosBOF;
			case -3: return adPosEOF;
		}
		return new PositionEnum_Param(__n);
	}
}

