// File: PropertyAttributesEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** PropertyAttributesEnum enumerated type */
public class PropertyAttributesEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adPropNotSupported */
	public static PropertyAttributesEnum adPropNotSupported = new PropertyAttributesEnum(0);

	/** enumerated constant adPropRequired */
	public static PropertyAttributesEnum adPropRequired = new PropertyAttributesEnum(1);

	/** enumerated constant adPropOptional */
	public static PropertyAttributesEnum adPropOptional = new PropertyAttributesEnum(2);

	/** enumerated constant adPropRead */
	public static PropertyAttributesEnum adPropRead = new PropertyAttributesEnum(512);

	/** enumerated constant adPropWrite */
	public static PropertyAttributesEnum adPropWrite = new PropertyAttributesEnum(1024);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected PropertyAttributesEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof PropertyAttributesEnum && __obj != null && ((PropertyAttributesEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static PropertyAttributesEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adPropNotSupported;
			case 1: return adPropRequired;
			case 2: return adPropOptional;
			case 512: return adPropRead;
			case 1024: return adPropWrite;
		}
		return new PropertyAttributesEnum(__n);
	}
}

