// File: RecordCreateOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** RecordCreateOptionsEnum enumerated type */
public class RecordCreateOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adCreateCollection */
	public static RecordCreateOptionsEnum adCreateCollection = new RecordCreateOptionsEnum(8192);

	/** enumerated constant adCreateStructDoc */
	public static RecordCreateOptionsEnum adCreateStructDoc = new RecordCreateOptionsEnum(-2147483648);

	/** enumerated constant adCreateNonCollection */
	public static RecordCreateOptionsEnum adCreateNonCollection = new RecordCreateOptionsEnum(0);

	/** enumerated constant adOpenIfExists */
	public static RecordCreateOptionsEnum adOpenIfExists = new RecordCreateOptionsEnum(33554432);

	/** enumerated constant adCreateOverwrite */
	public static RecordCreateOptionsEnum adCreateOverwrite = new RecordCreateOptionsEnum(67108864);

	/** enumerated constant adFailIfNotExists */
	public static RecordCreateOptionsEnum adFailIfNotExists = new RecordCreateOptionsEnum(-1);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected RecordCreateOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof RecordCreateOptionsEnum && __obj != null && ((RecordCreateOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static RecordCreateOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 8192: return adCreateCollection;
			case -2147483648: return adCreateStructDoc;
			case 0: return adCreateNonCollection;
			case 33554432: return adOpenIfExists;
			case 67108864: return adCreateOverwrite;
			case -1: return adFailIfNotExists;
		}
		return new RecordCreateOptionsEnum(__n);
	}
}

