// File: RecordOpenOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** RecordOpenOptionsEnum enumerated type */
public class RecordOpenOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adOpenRecordUnspecified */
	public static RecordOpenOptionsEnum adOpenRecordUnspecified = new RecordOpenOptionsEnum(-1);

	/** enumerated constant adOpenSource */
	public static RecordOpenOptionsEnum adOpenSource = new RecordOpenOptionsEnum(8388608);

	/** enumerated constant adOpenOutput */
	public static RecordOpenOptionsEnum adOpenOutput = new RecordOpenOptionsEnum(8388608);

	/** enumerated constant adOpenAsync */
	public static RecordOpenOptionsEnum adOpenAsync = new RecordOpenOptionsEnum(4096);

	/** enumerated constant adDelayFetchStream */
	public static RecordOpenOptionsEnum adDelayFetchStream = new RecordOpenOptionsEnum(16384);

	/** enumerated constant adDelayFetchFields */
	public static RecordOpenOptionsEnum adDelayFetchFields = new RecordOpenOptionsEnum(32768);

	/** enumerated constant adOpenExecuteCommand */
	public static RecordOpenOptionsEnum adOpenExecuteCommand = new RecordOpenOptionsEnum(65536);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected RecordOpenOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof RecordOpenOptionsEnum && __obj != null && ((RecordOpenOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static RecordOpenOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adOpenRecordUnspecified;
			case 8388608: return adOpenSource;
			// ** Duplicate ** case 8388608: return adOpenOutput;
			case 4096: return adOpenAsync;
			case 16384: return adDelayFetchStream;
			case 32768: return adDelayFetchFields;
			case 65536: return adOpenExecuteCommand;
		}
		return new RecordOpenOptionsEnum(__n);
	}
}

