// File: RecordsetEvents.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

public abstract class RecordsetEvents extends ezjcom.JComEventListener {

	/** Override this method to process the "WillChangeField" event. 
	  */
	public abstract void WillChangeField(int cFields, ezjcom.JComVariant Fields, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "FieldChangeComplete" event. 
	  */
	public abstract void FieldChangeComplete(int cFields, ezjcom.JComVariant Fields, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "WillChangeRecord" event. 
	  */
	public abstract void WillChangeRecord(SMS.EventReasonEnum adReason, int cRecords, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "RecordChangeComplete" event. 
	  */
	public abstract void RecordChangeComplete(SMS.EventReasonEnum adReason, int cRecords, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "WillChangeRecordset" event. 
	  */
	public abstract void WillChangeRecordset(SMS.EventReasonEnum adReason, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "RecordsetChangeComplete" event. 
	  */
	public abstract void RecordsetChangeComplete(SMS.EventReasonEnum adReason, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "WillMove" event. 
	  */
	public abstract void WillMove(SMS.EventReasonEnum adReason, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "MoveComplete" event. 
	  */
	public abstract void MoveComplete(SMS.EventReasonEnum adReason, SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "EndOfRecordset" event. 
	 * <P>Parameter <i>fMoreData</i> is IN/OUT.  It will be passed inside an array of size 1, so it can be modified.
	  */
	public abstract void EndOfRecordset(boolean[] fMoreData, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "FetchProgress" event. 
	  */
	public abstract void FetchProgress(int Progress, int MaxProgress, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Override this method to process the "FetchComplete" event. 
	  */
	public abstract void FetchComplete(SMS.Error pError, SMS.EventStatusEnum adStatus, SMS._Recordset pRecordset);

	/** Default constructor for COM-event listener object */

	public RecordsetEvents()
	{
		try{
			__JComEventListenerInit();
		} catch (ezjcom.JComException ex) {
			throw new RuntimeException( ex.toString());
		}
	}

	/** JNI functions used internally by EZ-JCom */
	private native boolean __JComEventListenerInit() throws ezjcom.JComException;
	static {
		System.loadLibrary( "JKCMSMS" );
	}

}

