// File: RecordStatusEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** RecordStatusEnum enumerated type */
public class RecordStatusEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adRecOK */
	public static RecordStatusEnum adRecOK = new RecordStatusEnum(0);

	/** enumerated constant adRecNew */
	public static RecordStatusEnum adRecNew = new RecordStatusEnum(1);

	/** enumerated constant adRecModified */
	public static RecordStatusEnum adRecModified = new RecordStatusEnum(2);

	/** enumerated constant adRecDeleted */
	public static RecordStatusEnum adRecDeleted = new RecordStatusEnum(4);

	/** enumerated constant adRecUnmodified */
	public static RecordStatusEnum adRecUnmodified = new RecordStatusEnum(8);

	/** enumerated constant adRecInvalid */
	public static RecordStatusEnum adRecInvalid = new RecordStatusEnum(16);

	/** enumerated constant adRecMultipleChanges */
	public static RecordStatusEnum adRecMultipleChanges = new RecordStatusEnum(64);

	/** enumerated constant adRecPendingChanges */
	public static RecordStatusEnum adRecPendingChanges = new RecordStatusEnum(128);

	/** enumerated constant adRecCanceled */
	public static RecordStatusEnum adRecCanceled = new RecordStatusEnum(256);

	/** enumerated constant adRecCantRelease */
	public static RecordStatusEnum adRecCantRelease = new RecordStatusEnum(1024);

	/** enumerated constant adRecConcurrencyViolation */
	public static RecordStatusEnum adRecConcurrencyViolation = new RecordStatusEnum(2048);

	/** enumerated constant adRecIntegrityViolation */
	public static RecordStatusEnum adRecIntegrityViolation = new RecordStatusEnum(4096);

	/** enumerated constant adRecMaxChangesExceeded */
	public static RecordStatusEnum adRecMaxChangesExceeded = new RecordStatusEnum(8192);

	/** enumerated constant adRecObjectOpen */
	public static RecordStatusEnum adRecObjectOpen = new RecordStatusEnum(16384);

	/** enumerated constant adRecOutOfMemory */
	public static RecordStatusEnum adRecOutOfMemory = new RecordStatusEnum(32768);

	/** enumerated constant adRecPermissionDenied */
	public static RecordStatusEnum adRecPermissionDenied = new RecordStatusEnum(65536);

	/** enumerated constant adRecSchemaViolation */
	public static RecordStatusEnum adRecSchemaViolation = new RecordStatusEnum(131072);

	/** enumerated constant adRecDBDeleted */
	public static RecordStatusEnum adRecDBDeleted = new RecordStatusEnum(262144);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected RecordStatusEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof RecordStatusEnum && __obj != null && ((RecordStatusEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static RecordStatusEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adRecOK;
			case 1: return adRecNew;
			case 2: return adRecModified;
			case 4: return adRecDeleted;
			case 8: return adRecUnmodified;
			case 16: return adRecInvalid;
			case 64: return adRecMultipleChanges;
			case 128: return adRecPendingChanges;
			case 256: return adRecCanceled;
			case 1024: return adRecCantRelease;
			case 2048: return adRecConcurrencyViolation;
			case 4096: return adRecIntegrityViolation;
			case 8192: return adRecMaxChangesExceeded;
			case 16384: return adRecObjectOpen;
			case 32768: return adRecOutOfMemory;
			case 65536: return adRecPermissionDenied;
			case 131072: return adRecSchemaViolation;
			case 262144: return adRecDBDeleted;
		}
		return new RecordStatusEnum(__n);
	}
}

