// File: ResyncEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** ResyncEnum enumerated type */
public class ResyncEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adResyncUnderlyingValues */
	public static ResyncEnum adResyncUnderlyingValues = new ResyncEnum(1);

	/** enumerated constant adResyncAllValues */
	public static ResyncEnum adResyncAllValues = new ResyncEnum(2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected ResyncEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof ResyncEnum && __obj != null && ((ResyncEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static ResyncEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adResyncUnderlyingValues;
			case 2: return adResyncAllValues;
		}
		return new ResyncEnum(__n);
	}
}

