// File: SaveOptionsEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** SaveOptionsEnum enumerated type */
public class SaveOptionsEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adSaveCreateNotExist */
	public static SaveOptionsEnum adSaveCreateNotExist = new SaveOptionsEnum(1);

	/** enumerated constant adSaveCreateOverWrite */
	public static SaveOptionsEnum adSaveCreateOverWrite = new SaveOptionsEnum(2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected SaveOptionsEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof SaveOptionsEnum && __obj != null && ((SaveOptionsEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static SaveOptionsEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adSaveCreateNotExist;
			case 2: return adSaveCreateOverWrite;
		}
		return new SaveOptionsEnum(__n);
	}
}

