// File: SeekEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** SeekEnum enumerated type */
public class SeekEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adSeekFirstEQ */
	public static SeekEnum adSeekFirstEQ = new SeekEnum(1);

	/** enumerated constant adSeekLastEQ */
	public static SeekEnum adSeekLastEQ = new SeekEnum(2);

	/** enumerated constant adSeekAfterEQ */
	public static SeekEnum adSeekAfterEQ = new SeekEnum(4);

	/** enumerated constant adSeekAfter */
	public static SeekEnum adSeekAfter = new SeekEnum(8);

	/** enumerated constant adSeekBeforeEQ */
	public static SeekEnum adSeekBeforeEQ = new SeekEnum(16);

	/** enumerated constant adSeekBefore */
	public static SeekEnum adSeekBefore = new SeekEnum(32);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected SeekEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof SeekEnum && __obj != null && ((SeekEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static SeekEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 1: return adSeekFirstEQ;
			case 2: return adSeekLastEQ;
			case 4: return adSeekAfterEQ;
			case 8: return adSeekAfter;
			case 16: return adSeekBeforeEQ;
			case 32: return adSeekBefore;
		}
		return new SeekEnum(__n);
	}
}

