// File: StreamReadEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** StreamReadEnum enumerated type */
public class StreamReadEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adReadAll */
	public static StreamReadEnum adReadAll = new StreamReadEnum(-1);

	/** enumerated constant adReadLine */
	public static StreamReadEnum adReadLine = new StreamReadEnum(-2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected StreamReadEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof StreamReadEnum && __obj != null && ((StreamReadEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static StreamReadEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case -1: return adReadAll;
			case -2: return adReadLine;
		}
		return new StreamReadEnum(__n);
	}
}

