// File: StreamWriteEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** StreamWriteEnum enumerated type */
public class StreamWriteEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adWriteChar */
	public static StreamWriteEnum adWriteChar = new StreamWriteEnum(0);

	/** enumerated constant adWriteLine */
	public static StreamWriteEnum adWriteLine = new StreamWriteEnum(1);

	/** enumerated constant stWriteChar */
	public static StreamWriteEnum stWriteChar = new StreamWriteEnum(0);

	/** enumerated constant stWriteLine */
	public static StreamWriteEnum stWriteLine = new StreamWriteEnum(1);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected StreamWriteEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof StreamWriteEnum && __obj != null && ((StreamWriteEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static StreamWriteEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 0: return adWriteChar;
			case 1: return adWriteLine;
			// ** Duplicate ** case 0: return stWriteChar;
			// ** Duplicate ** case 1: return stWriteLine;
		}
		return new StreamWriteEnum(__n);
	}
}

