// File: StringFormatEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** StringFormatEnum enumerated type */
public class StringFormatEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adClipString */
	public static StringFormatEnum adClipString = new StringFormatEnum(2);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected StringFormatEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof StringFormatEnum && __obj != null && ((StringFormatEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static StringFormatEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 2: return adClipString;
		}
		return new StringFormatEnum(__n);
	}
}

