// File: XactAttributeEnum.java
// Generated: Thu Oct 22 12:17:11 2015

// This Java source file has been automatically
// generated by EZ-JCom.

package SMS;

/** XactAttributeEnum enumerated type */
public class XactAttributeEnum extends ezjcom.JComEnumeration {


	/** enumerated constant adXactCommitRetaining */
	public static XactAttributeEnum adXactCommitRetaining = new XactAttributeEnum(131072);

	/** enumerated constant adXactAbortRetaining */
	public static XactAttributeEnum adXactAbortRetaining = new XactAttributeEnum(262144);

	/** enumerated constant adXactAsyncPhaseOne */
	public static XactAttributeEnum adXactAsyncPhaseOne = new XactAttributeEnum(524288);

	/** enumerated constant adXactSyncPhaseOne */
	public static XactAttributeEnum adXactSyncPhaseOne = new XactAttributeEnum(1048576);


	/** Default constructor (protected; use intToEnumeratedValue to obtain enumerated values from integers.) */
	protected XactAttributeEnum( int __n ) { __Ezj_value = __n; }

	/** Compare two enumerated values for being equal */
	public boolean equals( Object __obj ) { return __obj instanceof XactAttributeEnum && __obj != null && ((XactAttributeEnum)__obj).getEnumeratedIntValue() == __Ezj_value; }

	/** Returns an enumerated value corresponding to a given integer. */
	public static XactAttributeEnum intToEnumeratedValue( int __n ) {
		switch ( __n  ) {
			case 131072: return adXactCommitRetaining;
			case 262144: return adXactAbortRetaining;
			case 524288: return adXactAsyncPhaseOne;
			case 1048576: return adXactSyncPhaseOne;
		}
		return new XactAttributeEnum(__n);
	}
}

